import{a as p,S as g,i as c}from"./assets/vendor-ee72e1a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function f(o,t){const s="44064586-c85ee0d0f4282a04fbc0070f7",l="https://pixabay.com/api/",r={params:{key:s,q:o,safesearch:!0,image_type:"photo",orientation:"horizontal",per_page:15,page:t}};try{return(await p.get(l,r)).data}catch(n){throw n}}const h=async o=>{if(o.length===0)return iziToast.error({message:"Sorry, there are no images matching your search. Please try again!"});let t="";const s=document.querySelector(".gallery-list");s!=null&&(t=s.innerHTML),t+=await o.map(e=>`
        <li class="gallery-item" id=${e.id}>
          <a class="gallery-link" href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}"></a>
            <ul class="item-info">
              <li><h3>Likes</h3><p>${e.likes}</p></li>
              <li><h3>Views</h3><p>${e.views}</p></li> 
              <li><h3>Comments</h3><p>${e.comments}</p></li> 
              <li><h3>Downloads</h3><p>${e.downloads}</p></li> 
            </ul> 
        </li>
    `).join(""),gallery.innerHTML=`<ul class="gallery gallery-list">${t}</ul>`;var l=new g(".gallery a",{captionsData:"alt",captionDelay:300});l.refresh()},d=document.getElementById("searchForm"),b=document.getElementById("searchInput"),y=document.getElementById("loader"),w=document.getElementById("gallery"),a=document.getElementById("load_more_btn");a.style.display="none";let i=1,u="";const L=()=>{i+=1,m(i)};a.addEventListener("click",L);d.addEventListener("submit",async o=>{if(o.preventDefault(),u=b.value.trim(),u===""){c.error({title:"Error:",message:"Please enter a search term.",position:"topRight"});return}w.innerHTML="",i=1,m(i)});const m=async o=>{try{y.style.display="block",a.style.display="none";const t=await f(u,o),s=t.hits;if(await h(s),o>1&&I(),t.total<=o*15){c.info({message:"We're sorry, but you've reached the end of search results."});return}a.style.display="inline-block"}catch{c.error({title:"Error:",message:"An error occurred while fetching images. Please try again later."})}finally{y.style.display="none",d.reset()}},I=()=>{const s=document.querySelector(".gallery-item").getBoundingClientRect().height*2;window.scrollBy({top:s,left:0,behavior:"smooth"})};
//# sourceMappingURL=commonHelpers.js.map
